"""Initial schema: users, families, guardians, children, stage events, interactions

Revision ID: 5a5581a170d4
Revises: 
Create Date: 2026-09-28 01:39:24.226453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5581a170d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_name', sa.String(length=160), nullable=False),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('referral_source', sa.String(length=80), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_families_family_name'), ['family_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('program', sa.String(length=80), nullable=True),
    sa.Column('classroom', sa.String(length=80), nullable=True),
    sa.Column('desired_start_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('inquiry_date', sa.Date(), nullable=True),
    sa.Column('contacted_date', sa.Date(), nullable=True),
    sa.Column('tour_scheduled_date', sa.Date(), nullable=True),
    sa.Column('tour_completed_date', sa.Date(), nullable=True),
    sa.Column('waitlist_date', sa.Date(), nullable=True),
    sa.Column('enrolled_date', sa.Date(), nullable=True),
    sa.Column('active_date', sa.Date(), nullable=True),
    sa.Column('graduated_date', sa.Date(), nullable=True),
    sa.Column('declined_date', sa.Date(), nullable=True),
    sa.Column('decline_reason', sa.String(length=120), nullable=True),
    sa.Column('decline_notes', sa.Text(), nullable=True),
    sa.Column('withdrew_date', sa.Date(), nullable=True),
    sa.Column('withdraw_reason', sa.String(length=120), nullable=True),
    sa.Column('withdraw_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_children_stage'), ['stage'], unique=False)

    op.create_table('guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('relationship_to_child', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardians_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardians_family_id'), ['family_id'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_family_id'), ['family_id'], unique=False)

    op.create_table('stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_stage', sa.String(length=40), nullable=True),
    sa.Column('to_stage', sa.String(length=40), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_events_child_id'), ['child_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_events_child_id'))

    op.drop_table('stage_events')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_family_id'))
        batch_op.drop_index(batch_op.f('ix_interactions_child_id'))

    op.drop_table('interactions')
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardians_family_id'))
        batch_op.drop_index(batch_op.f('ix_guardians_email'))

    op.drop_table('guardians')
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_stage'))
        batch_op.drop_index(batch_op.f('ix_children_family_id'))

    op.drop_table('children')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_families_family_name'))

    op.drop_table('families')
    # ### end Alembic commands ###
